name: Publish (pypi)

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PYTHON_PACKAGE_NAME: YOUR_PYTHON_PACKAGE_NAME
      PYTHON_NAME_SPACE: YOUR_PYTHON_NAME_SPACE
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Publish
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
        run: |
          bash dev/publish.sh "pypi"

  test-published-package:
    needs:
      - publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    env:
      PYTHON_PACKAGE_NAME: YOUR_PYTHON_PACKAGE_NAME
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      # It takes some time when the package gets available.
      - name: Sleep
        run: |
          sleep 30
      - name: Install package
        run: |
          python3 -m pip install -U "${{ env.PYTHON_PACKAGE_NAME}}"
      - name: Test package
        run: |
          uv run python -m "${{ env.PYTHON_NAME_SPACE }}"
