name: Test publish (testpypi)

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: package version
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Set up trunk
        uses: trunk-io/trunk-action/setup@v1
      - name: Test publish
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.TESTPYPI_API_TOKEN }}"
          PACKAGE_VERSION: "${{ inputs.package_version }}"
        run: |
          bash dev/publish.sh testpypi

  test-published-package:
    needs:
      - publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    env:
      PYTHON_PACKAGE_NAME: YOUR_PYTHON_PACKAGE_NAME
      PYTHON_NAME_SPACE: YOUR_PYTHON_NAME_SPACE
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Install packages
        env:
          PACKAGE_VERSION: "${{ inputs.package_version }}"
        run: |
          python3 -m pip install -U pip
          python3 -m pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple/ \
            --force-reinstall \
            -U "${PYTHON_PACKAGE_NAME}==${PACKAGE_VERSION}"
      # It takes some time when the package gets available.
      - name: Sleep
        run: |
          sleep 30
      - name: Test package
        run: |
          python -c 'python -m ${PYTHON_NAME_SPACE}'
